name: Python package

on: [push]

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history, required for diffing revisions
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run difflog
        # Generate a changelog from the last tag to HEAD
        run: python -m difflog.git_report --from-rev $(git describe --tags --abbrev=0 HEAD^) --to-rev HEAD > $GITHUB_STEP_SUMMARY
